//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group3_MVC4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRequest
    {
        public int Id { get; set; }
        public string MemberId { get; set; }
        public Nullable<int> OwnedWatch { get; set; }
        public Nullable<int> WishWatch { get; set; }
        public string ConfirmCode { get; set; }
        public bool Status { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Watch Watch { get; set; }
        public virtual Watch Watch1 { get; set; }
    }
}
