//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group3_MVC4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.ExchangeRequests = new HashSet<ExchangeRequest>();
            this.Watches = new HashSet<Watch>();
        }
    
        public string Id { get; set; }
        public string Phone { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> WorkAt { get; set; }
        public string Password { get; set; }
        public string ConfirmCode { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<ExchangeRequest> ExchangeRequests { get; set; }
        public virtual Role Role { get; set; }
        public virtual Store Store { get; set; }
        public virtual ICollection<Watch> Watches { get; set; }
    }
}
