//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group3_MVC4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Phone { get; set; }
        public System.DateTime OrderDate { get; set; }
        public bool Status { get; set; }
        public string ConfirmCode { get; set; }
    
        public virtual BuyOrder BuyOrder { get; set; }
        public virtual SellOrder SellOrder { get; set; }
    }
}
