//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group3_MVC4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellOrder
    {
        public int Id { get; set; }
        public int WatchId { get; set; }
        public double Price { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Watch Watch { get; set; }
    }
}
