//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group3_MVC4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WatchShopEntities : DbContext
    {
        public WatchShopEntities()
            : base("name=WatchShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<BuyOrder> BuyOrders { get; set; }
        public virtual DbSet<ExchangeRequest> ExchangeRequests { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SellOrder> SellOrders { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Timepeice> Timepeices { get; set; }
        public virtual DbSet<WallLock> WallLocks { get; set; }
        public virtual DbSet<Watch> Watches { get; set; }
        public virtual DbSet<WristWatch> WristWatches { get; set; }
    }
}
