//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group3_MVC4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WristWatch
    {
        public int Id { get; set; }
        public string Size { get; set; }
        public bool Gender { get; set; }
        public bool WatchType { get; set; }
        public bool IsSmartWatch { get; set; }
        public Nullable<int> WaterProof { get; set; }
    
        public virtual Watch Watch { get; set; }
    }
}
